#!/usr/bin/env bash
# Wrap the SPM-built executable as WriterFlow.app.
# Xcode is not required — Command Line Tools + swift build is enough.
set -euo pipefail

CONFIG="${1:-debug}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "▸ swift build -c ${CONFIG}"
swift build -c "${CONFIG}"

BIN_PATH="$(swift build -c "${CONFIG}" --show-bin-path)"
EXE="${BIN_PATH}/WriterFlow"
[[ -x "$EXE" ]] || { echo "✗ executable not found at $EXE" >&2; exit 1; }

APP="build/WriterFlow.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$EXE" "$APP/Contents/MacOS/WriterFlow"
cp Info.plist "$APP/Contents/Info.plist"

# App icon (Finder, DMG installer, Applications). Generated by packaging/generate-assets.py.
ICON="packaging/AppIcon.icns"
if [[ -f "$ICON" ]]; then
    cp "$ICON" "$APP/Contents/Resources/AppIcon.icns"
else
    echo "✗ $ICON not found — run: python3 packaging/generate-assets.py" >&2
    exit 1
fi

# Required third-party license notices must travel inside the distributed artifact.
NOTICE="THIRD-PARTY-NOTICES.txt"
if [[ -f "$NOTICE" ]]; then
    cp "$NOTICE" "$APP/Contents/Resources/$NOTICE"
else
    echo "✗ $NOTICE not found — required third-party license notice is missing" >&2
    exit 1
fi

# Copy processed resource bundle if it exists (SwiftPM emits WriterFlow_WriterFlow.bundle).
BUNDLE="${BIN_PATH}/WriterFlow_WriterFlow.bundle"
if [[ -d "$BUNDLE" ]]; then
    cp -R "$BUNDLE" "$APP/Contents/Resources/"
fi

# SQLCipher is linked as @rpath/SQLCipher.framework — copy the macOS slice from
# SPM's binary artifact into Contents/Frameworks so `open WriterFlow.app` works
# outside of `swift run` (which resolves rpath via the build directory).
SQLCIPHER_XCFRAMEWORK="${ROOT}/.build/artifacts/sqlcipher.swift/SQLCipher/SQLCipher.xcframework"
SQLCIPHER_FRAMEWORK="${SQLCIPHER_XCFRAMEWORK}/macos-arm64_x86_64/SQLCipher.framework"
if [[ -d "$SQLCIPHER_FRAMEWORK" ]]; then
    mkdir -p "$APP/Contents/Frameworks"
    rm -rf "$APP/Contents/Frameworks/SQLCipher.framework"
    cp -R "$SQLCIPHER_FRAMEWORK" "$APP/Contents/Frameworks/"
    install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP/Contents/MacOS/WriterFlow" 2>/dev/null || true
else
    echo "✗ $SQLCIPHER_FRAMEWORK not found — run 'swift build' first so SPM fetches SQLCipher" >&2
    exit 1
fi

# Signing identity.
#
# Debug/local installs prefer a self-signed certificate ("WriterFlow Local
# Signing", created by scripts/create-signing-cert.sh). An ad-hoc signature's
# designated requirement is a bare cdhash that changes with every build, so
# macOS treats each rebuild as a different app and no Keychain "Always Allow"
# ever survives — users get re-prompted for their password forever. A
# certificate yields a stable `certificate leaf` requirement instead. Still
# not Developer ID and still no Apple Developer account (ADR-0010): Gatekeeper
# approval remains manual.
#
# Release stays ad-hoc by default so the public DMG story in RELEASE.md /
# ADR-0010 is unchanged. Override with WRITERFLOW_SIGNING_IDENTITY only when
# intentionally packaging under a different identity.
DEFAULT_IDENTITY="WriterFlow Local Signing"
IDENTITY="${WRITERFLOW_SIGNING_IDENTITY:-}"
if [[ -z "$IDENTITY" ]]; then
    if [[ "$CONFIG" == "release" ]]; then
        IDENTITY="-"
    elif security find-identity -v -p codesigning | grep -q "$DEFAULT_IDENTITY"; then
        IDENTITY="$DEFAULT_IDENTITY"
    else
        echo "⚠ no local code-signing identity found — falling back to ad-hoc." >&2
        echo "  Keychain prompts will recur on every rebuild. Fix with: scripts/create-signing-cert.sh" >&2
        IDENTITY="-"
    fi
fi

# Release is a production packaging step: hardened runtime (the v1 default per
# RELEASE.md) and hard-fail on error, so the script never silently ships an
# unsigned or non-hardened artifact. Debug stays non-fatal so a signing hiccup
# does not block the local loop, but it warns rather than swallowing the error.
if [[ "$CONFIG" == "release" ]]; then
    echo "▸ codesigning with hardened runtime (release), identity: ${IDENTITY}"
    codesign --force --sign "$IDENTITY" --options runtime --timestamp=none \
        --entitlements "$ROOT/WriterFlow.entitlements" "$APP"
else
    echo "▸ codesigning (debug), identity: ${IDENTITY}"
    codesign --force --sign "$IDENTITY" --timestamp=none "$APP" \
        || echo "⚠ codesign failed — the app will keep prompting for Keychain access" >&2
fi

echo "▸ built $APP"
